# Default values for chaosblade.

# chaosblade-operator
operator:
  repository: chaosbladeio/chaosblade-operator
  #  repository: "registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-operator"
  version: 0.6.0
  # image.pullPolicy: must be Always|IfNotPresent|Never
  pullPolicy: IfNotPresent

env:
  logLevel: info

webhook:
  enable: false
