# Default values for chaosblade.

# chaosblade-operator
operator:
#  repository: chaosbladeio/chaosblade-operator
  repository: "registry-vpc.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-operator"
  version: 0.7.0-dev
  # image.pullPolicy: must be Always|IfNotPresent|Never
  pullPolicy: IfNotPresent

env:
  logLevel: info

webhook:
  enable: false
